<?php

namespace ContainerSL5E3Mj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y_Pi5vYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y.pi5vY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y.pi5vY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'userToFollow' => ['privates', 'App\\Entity\\User', 'getUserService', true],
        ], [
            'doctrine' => '?',
            'userToFollow' => 'App\\Entity\\User',
        ]);
    }
}
