<?php

namespace ContainerAmz4BaJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L0k_WYVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L0k.WYV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L0k.WYV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'comment' => ['privates', '.errored..service_locator.L0k.WYV.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.L0k.WYV": it needs an instance of "App\\Entity\\Comment" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'repository' => 'App\\Repository\\CommentRepository',
        ]);
    }
}
