<?php

namespace ContainerAmz4BaJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SpN9U5_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.spN9U5.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.spN9U5.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'userToUnfollow' => ['privates', '.errored..service_locator.spN9U5..App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.spN9U5.": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'userToUnfollow' => 'App\\Entity\\User',
        ]);
    }
}
