<?php

namespace ContainerGOQwYsH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HOk5OQwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HOk5OQw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HOk5OQw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.HOk5OQw.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.HOk5OQw": it needs an instance of "App\\Entity\\Post" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'post' => 'App\\Entity\\Post',
            'repository' => 'App\\Repository\\PostRepository',
            'slugger' => '?',
        ]);
    }
}
