<?php

namespace ContainerGOQwYsH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OfDrtWWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OfDrtWW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OfDrtWW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posts' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.OfDrtWW.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.OfDrtWW": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'posts' => 'App\\Repository\\PostRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
