<?php

namespace ContainerGOQwYsH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetMapper_Command_DebugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'asset_mapper.command.debug' shared service.
     *
     * @return \Symfony\Component\AssetMapper\Command\DebugAssetMapperCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/asset-mapper/Command/DebugAssetMapperCommand.php';

        $container->privates['asset_mapper.command.debug'] = $instance = new \Symfony\Component\AssetMapper\Command\DebugAssetMapperCommand(($container->privates['asset_mapper'] ?? self::getAssetMapperService($container)), ($container->privates['asset_mapper.repository'] ??= new \Symfony\Component\AssetMapper\AssetMapperRepository(['assets/' => ''], \dirname(__DIR__, 4), ['#^(?=[^\\.]).*/(?=[^\\.])assets/(?=[^\\.])styles/(?=[^\\.])app\\.css$#'])), \dirname(__DIR__, 4));

        $instance->setName('debug:asset-map');
        $instance->setDescription('Outputs all mapped assets.');

        return $instance;
    }
}
