<?php

namespace ContainerGOQwYsH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4TPgo9W.App\Entity\Board' shared service.
     *
     * @return \App\Entity\Board
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4TPgo9W": it needs an instance of "App\\Entity\\Board" but this type has been excluded in "config/services.yaml".');
    }
}
