<?php

namespace ContainerUwer3xv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4TPgo9WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4TPgo9W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4TPgo9W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'board' => ['privates', 'App\\Entity\\Board', 'getBoardService', true],
            'repository' => ['privates', 'App\\Repository\\BoardRepository', 'getBoardRepositoryService', true],
        ], [
            'board' => 'App\\Entity\\Board',
            'repository' => 'App\\Repository\\BoardRepository',
        ]);
    }
}
