<?php

namespace ContainerUwer3xv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Comment' shared autowired service.
     *
     * @return \App\Entity\Comment
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Comment.php';

        return $container->privates['App\\Entity\\Comment'] = new \App\Entity\Comment();
    }
}
