<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAmz4BaJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAmz4BaJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAmz4BaJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAmz4BaJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAmz4BaJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Amz4BaJ',
    'container.build_id' => '7e5518b8',
    'container.build_time' => 1700314785,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAmz4BaJ');
