<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUwer3xv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUwer3xv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUwer3xv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUwer3xv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUwer3xv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uwer3xv',
    'container.build_id' => 'e292b528',
    'container.build_time' => 1700514718,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUwer3xv');
