<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLijM6GU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLijM6GU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLijM6GU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLijM6GU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLijM6GU\App_KernelDevDebugContainer([
    'container.build_hash' => 'LijM6GU',
    'container.build_id' => '10476f2e',
    'container.build_time' => 1697107582,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLijM6GU');
